export default function Head(){
    return (
        <>
            <title>About page</title>
            <meta content="width=device-width, initial-scale=1"/>
            <meta name="description" content="Generated by Create React App"/>
            <link rel="icon" href="/favicon.ico"/>
        </>
    )
}